# Generated by Django 2.1.3 on 2018-12-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('imagePath', models.ImageField(default='', upload_to='testLoad')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
