# Generated by Django 2.1.3 on 2019-04-07 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_application', '0002_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
