# Generated by Django 2.1.3 on 2019-04-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_application', '0003_event_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
