# Generated by Django 2.1.3 on 2019-04-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_application', '0005_eventprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='event_user',
            field=models.BooleanField(null=True),
        ),
    ]
