# Generated by Django 2.1.3 on 2019-04-09 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_application', '0006_auto_20190409_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
