# Generated by Django 2.1.3 on 2018-12-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgNameGen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imagePath',
            field=models.ImageField(default='', upload_to='', verbose_name='/testLoad'),
        ),
    ]
