# Generated by Django 2.1.3 on 2018-12-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgNameGen', '0002_image_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagePath',
            field=models.ImageField(default='', upload_to='testLoad'),
        ),
    ]
